name: Run Robot Framework Tests

on:
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Robot Tests
        run: |
          robot -d results tests/
        
      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: Robot Results
          path: results/
