name: Run Robot Framework Tests

on:
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Robot Tests
        run: |
          robot -d results tests/
        
      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Robot Results
          path: results/
      - name: Send Notification to Slack
        if: always()
        run: |
          curl -X POST -H 'Content-type: application/json' \
          --data '{"text":"🚀 Robot Framework tests have completed! Check the results."}' \
          ${{ secrets.SLACK_WEBHOOK_URL }}
